### ISSUE TITLE
Intermittent 'MemoryError' in googleapiclient's discovery.py

### ISSUE THREAD

**Issue by tehfink** [nithinmurali/pygsheets#202]
I have a periodic script which appends sensor data to a Google Sheet every minute, on a FreeBSD 11 VPS with 4GB, Python 3.6.4, and 1.1.4. Seemingly randomly (maybe every 20 minutes?) the following 2 versions of the same error pop up:

```python

ERROR Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/huey/consumer.py", line 169, in process_task
    task_value = self.huey.execute(task)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/huey/api.py", line 357, in execute
    result = task.execute()
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/huey/api.py", line 841, in execute
    return func(*args, **kwargs)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/huey/contrib/djhuey/__init__.py", line 108, in inner
    return fn(*args, **kwargs)
  File "/usr/local/www/…/gather/tasks.py", line 25, in gather_SensorVGTicker
    append_SensorVG_monthly_spreadsheet(ds)
  File "/usr/local/www/…/gather/google_drive.py", line 119, in append_SensorVG_monthly_spreadsheet
    worksheet.append_table(start='A2', end=None, values=list(ticker_dict.values()), dimension='ROWS', overwrite=True)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/pygsheets/worksheet.py", line 831, in append_table
    self.client.sh_append(self.spreadsheet.id, body=body, rranage=self._get_range(start, end), replace=overwrite)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/pygsheets/client.py", line 430, in sh_append
    final_request = self.service.spreadsheets().values().append(spreadsheetId=spreadsheet_id, range=rranage, body=body,
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1118, in methodResource
    schema=schema)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1023, in __init__
    self._set_service_methods()
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1058, in _set_service_methods
    self._add_basic_methods(self._resourceDesc, self._rootDesc, self._schema)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1088, in _add_basic_methods
    methodName, methodDesc, rootDesc, schema)
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 931, in createMethod
    setattr(method, '__doc__', ''.join(docs))
MemoryError
```
or:
```python
…
  File "/usr/local/www/…-virtualenv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 913, in createMethod
    schema.prettyPrintByName(paramdesc['$ref'])))
MemoryError
```

Interestingly, there is still ~22% free memory on the VPS.
I realize that the issue could probably lie with googleapiclient, but just wanted to ask if anyone had seen something like this before, or had suggestions for debugging.

**Comment by tehfink** [comment]
In case it helps anyone, I traced this back to `oauth2client._helpers`, which seems to point to this function as the culprit:
```python
@functools.wraps(wrapped)
def positional_wrapper(…
```
It can blow up to 20MB on each call. Anyway, I worked around this by commenting out the entire 'doc' section in `googleapiclient.discovery` (lines 878-931).

**Comment by nithinmurali** [comment]
should be fixed as `oauth2client` dependency is removed.

**Comment by willjhenry** [comment]
I am using pygsheets and noticing a possible memory leak issue. I am using it on AppEngine and the memory steadily increases until the instance is forced to reboot. I have narrowed where I think the leak is to the lines of code that connect to the worksheet and ingest some data. Im wondering if there still might be an issue here?
