### ISSUE TITLE
import pygsheets gives error in root but not as pi user

### ISSUE THREAD

**Issue by Ricardosgeral** [nithinmurali/pygsheets#214]
Hi

I can use pysheets with no problem as pi user

but when i try to use as root I have this error

root@raspberrypi:/home/pi/erotes# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygsheets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pygsheets/__init__.py", line 15, in <module>
    from .client import Client, authorize
  File "/usr/local/lib/python3.5/dist-packages/pygsheets/client.py", line 31, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/service_account.py", line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python3.5/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
  ImportError: cannot import name 'opentype'

Is there any additional procedure to use as root?
thanks

**Comment by Ricardosgeral** [comment]
I need to run as root since i'm starting a python script @reboot in crontab -e

**Comment by Ricardosgeral** [comment]
I've solve it by upgrading pyasn1-modules

`pip3 install --upgrade pyasn1-modules`
