### ISSUE TITLE
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by pradyjswl** [nithinmurali/pygsheets#235]
why I am getting this error ?
I am using request module to call an API 280 times in for loop and storing the data into dataframe.
I get two dataframe of 280*370. before I start the loop I have 30min of sleep time.  I am writing these two dataframe into two sheet of googlesheet. I keep getting this error. Not sure if googleapi is not allowing me to write these large amount of data, or is it my login token has expired because i waited 30minute ? or is it pygsheet limitation that how much data can be written into google sheet at a time ?

PS : I am new to python programming, and learning how it works.
```
Traceback (most recent call last):
  File "C:/Users/pradeep.jaiswal/Downloads/Python/Test.py", line 333, in <module>
    _1_main()
  File "C:/Users/pradeep.jaiswal/Downloads/Python/Test.py", line 326, in _1_main
    _11_calculate_candle()  # calculate candle volume
  File "C:/Users/pradeep.jaiswal/Downloads/Python/Test.py", line 274, in _11_calculate_candle
    bv_sh.set_dataframe(master_bv_df, (1, 1), copy_index=True, copy_head=True)  # row index starts with 1
  File "C:\Program Files\Python36\lib\site-packages\pygsheets\worksheet.py", line 1001, in set_dataframe
    self.update_cells(crange=crange, values=values)
  File "C:\Program Files\Python36\lib\site-packages\pygsheets\worksheet.py", line 520, in update_cells
    self.client.sh_update_range(self.spreadsheet.id, body, self.spreadsheet.batch_mode, parse=parse)
  File "C:\Program Files\Python36\lib\site-packages\pygsheets\client.py", line 411, in sh_update_range
    self._execute_request(spreadsheet_id, final_request, batch)
  File "C:\Program Files\Python36\lib\site-packages\pygsheets\client.py", line 455, in _execute_request
    response = request.execute()
  File "C:\Program Files\Python36\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\googleapiclient\http.py", line 835, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Program Files\Python36\lib\site-packages\googleapiclient\http.py", line 162, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Program Files\Python36\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Program Files\Python36\lib\site-packages\httplib2\__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Python36\lib\site-packages\httplib2\__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Python36\lib\site-packages\httplib2\__init__.py", line 996, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "C:\Program Files\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python36\lib\ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "C:\Program Files\Python36\lib\ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "C:\Program Files\Python36\lib\ssl.py", line 636, in write
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

**Comment by pradyjswl** [comment]
I have sheet.set_dataframe(df) at multiple places in my code, every time it fails for one or another places having sheet.set_dataframe . Though some of the them gets passed correctly, before failing for the next line

**Comment by stdavis** [comment]
Did you ever find a solution? I'm experiencing the same error.

**Comment by nithinmurali** [comment]
Please provide steps to reproduce the this.

**Comment by stdavis** [comment]
My situation happens with a very long running process (several hours). I think that I have it fixed by using some try/catch and reauthorizing.

**Comment by nithinmurali** [comment]
Closing for now. feel free to reopen again if you find this issue again or a way to reproduce this.
