### ISSUE TITLE
EOF when reading a line

### ISSUE THREAD

**Issue by Avinash-Raj** [nithinmurali/pygsheets#24]
I got the below error.

```Python
File "/home/gae-backup/lib/oauth2client/tools.py", line 239, in run_flow     
code = input('Enter verification code: ').strip() EOFError: 
```

**Comment by nithinmurali** [comment]
Please provide your Environment Info(os and python version) , and steps to reproduce . also a complete stack-trace will be helpful.

**Comment by Avinash-Raj** [comment]
I'm trying to check oauth2 locally on my GAE application which runs on Ubuntu 14.04. Y

Full traceback..
```

Enter verification code: Internal Server Error: /alumni_dateycollege/sheet/
Traceback (most recent call last):
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/alumni_registration_dateycollege/views.py", line 56, in testsheet
    creat_sample_sheet()
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/alumni_registration_dateycollege/sheet_handler.py", line 7, in creat_sample_sheet
    gc = pygsheets.authorize(outh_file=client_secret_file)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/pygsheets/client.py", line 437, in authorize
    credentials = get_outh_credentials(client_secret_file=outh_file, credential_dir=outh_creds_store)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/pygsheets/client.py", line 407, in get_outh_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/oauth2client/tools.py", line 239, in run_flow
    code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
ERROR    2016-11-29 05:44:31,412 base.py:284] Internal Server Error: /alumni_dateycollege/sheet/
Traceback (most recent call last):
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/alumni_registration_dateycollege/views.py", line 56, in testsheet
    creat_sample_sheet()
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/alumni_registration_dateycollege/sheet_handler.py", line 7, in creat_sample_sheet
    gc = pygsheets.authorize(outh_file=client_secret_file)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/pygsheets/client.py", line 437, in authorize
    credentials = get_outh_credentials(client_secret_file=outh_file, credential_dir=outh_creds_store)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/pygsheets/client.py", line 407, in get_outh_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/gemini/.up_projects/vishudha-gae-backup/vishudha-gae-backup/lib/oauth2client/tools.py", line 239, in run_flow
    code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
INFO     2016-11-29 05:44:31,598 module.py:794] default: "GET /alumni_dateycollege/sheet/ HTTP/1.1" 500 80331
```

**Comment by nithinmurali** [comment]
Can you try,
```
import pygsheets
gc = pygsheets.authorize(outh_file= <relative path to client secret file>)
ss = gc.open('<some sheet you have>')
```
and see if you are able to authorize

**Comment by Avinash-Raj** [comment]
@nithinmurali error raised because of the above code.. Pls add a tutorial on how to link pygsheets with Google App Engine..

**Comment by nithinmurali** [comment]
@Avinash-Raj I have no experience with Google App Engine , so wont be able to write a tutorial as of now. Are you getting the same  `EOFError` when just running these statements?

**Comment by nithinmurali** [comment]
added non local authorization in #26 . Which should fix this. see [docs](http://pygsheets.readthedocs.io/en/latest/authorizing.html#oauth-credentials) about non local authorization. Re open if the issue still persists.
