### ISSUE TITLE
Error when exception contains accents

### ISSUE THREAD

**Issue by pc-tradelab** [nithinmurali/pygsheets#255]
Hello,

when the API returns an error with an accent (for exemple) in the message, an exception is raised. 
```
Traceback (most recent call last):
  File "/home/pc/anaconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/pc/work/analyse_spark/durandal/audience_lab/test/test_gsheets.py", line 18, in test_creattion
    service.add_dataframe_to_new_worksheet(df, "Feuille 1")
  File "/home/pc/work/analyse_spark/durandal/audience_lab/client/gsheet_service.py", line 40, in add_dataframe_to_new_worksheet
    ws = sh.add_worksheet(name)
  File "/home/pc/anaconda2/lib/python2.7/site-packages/pygsheets/spreadsheet.py", line 208, in add_worksheet
    result = self.client.sh_batch_update(self.id, request, 'replies/addSheet', False)
  File "/home/pc/anaconda2/lib/python2.7/site-packages/pygsheets/client.py", line 443, in sh_batch_update
    return self._execute_request(spreadsheet_id, final_request, batch)
  File "/home/pc/anaconda2/lib/python2.7/site-packages/pygsheets/client.py", line 457, in _execute_request
    if repr(e).find('timed out') == -1:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 225: ordinal not in range(128)
```

**Comment by nithinmurali** [comment]
Hi, This is fixed in the staging and will be rolled out in next version. You can get it from the staging branch. 

`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip`
