### ISSUE TITLE
pygsheets.exceptions.RequestError: Timeout : timeout('timed out',)

### ISSUE THREAD

**Issue by anandgokul18** [nithinmurali/pygsheets#274]
I wrote a script that uses pygsheets to update a Google Sheet. I had setup a cron job to run this script daily. Suddenly, it stopped working with this error: "pygsheets.exceptions.RequestError: Timeout : timeout('timed out',)". 

If I try to run from my laptop (macOS), it is working fine, but, if I try to run this from my Linux machine, it throws up this error.

Also, the code is failing at 'authorize()' itself which is weird. The service account key is all correct (since it works from my laptop)

_Traceback (most recent call last):_
  _File "rackSheet.py", line 190, in <module>
    gc = pygsheets.authorize(service_file='/home/anandgokul/BangaloreRackSheet-Script/mypkey.json')_
  _File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 595, in authorize
    rclient = Client(oauth=credentials, **client_kwargs)_
  _File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 84, in __init__
    self._spreadsheeets = self._fetch_sheets()_
  _File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 99, in _fetch_sheets
    results = self._execute_request(None, request, False)_
  _File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 460, in _execute_request
    raise RequestError("Timeout : " + repr(e))_
_pygsheets.exceptions.RequestError: Timeout : timeout('timed out',)_

I am not sure why it stopped working all of a sudden. I also tried setting 'retries=5' inside authorize() attribute as per https://github.com/nithinmurali/pygsheets/issues/84, but no use.

I looked up the RequestError in your code and it means that the script is unable to connect to Google Api. Any idea why this issue is happening?

I hope my explanation above is clear. Any help or guidance will be appreciated.

Thank you

**Comment by nithinmurali** [comment]
what is your pygsheets version? is your internet working fine? do you have any proxy ?

**Comment by anandgokul18** [comment]
Version: 1.1.4

Yes, internet is working fine. 

I think there might be an permission issue in accessing cache folder at /tmp. Will this cause any issue in authorize() and if so, is there a way to turn off caching?

**Comment by nithinmurali** [comment]
No, caching shouldn't affect the authorize. anyway, you can use `no_cache=False`  to turn off caching.

**Comment by anandgokul18** [comment]
Any other reason why this might be happening then?

**Comment by nithinmurali** [comment]
Nothing i can think of. You can try updating to the master version (to be released as 1.2). The auth backend and request handling is changed. See if that makes any difference. But please not that there are few unbreakable changes.

`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip`

**Comment by anandgokul18** [comment]
I tried the same. Still, issue is seen. I tried with gspread as well, it gets stuck indefinitely in the authorize function call, looks like gspread hasn't handled this.

I'm guessing it has something to do with my company firewall or misconfiguration on the device, and not a bug with pygsheets as such. So, closing this. 

Thanks for help

**Comment by nithinmurali** [comment]
As a last resort you can try using the api directly by using the google python api client .

**Comment by anandgokul18** [comment]
Yes, that's what I plan on doing as one last hope

**Comment by lidatou1991** [comment]
> what is your pygsheets version? is your internet working fine? do you have any proxy ?

I am using proxy to access google server since I am in China. I am coming across the same operation time out problem.  More details in stackover flow question [.](https://stackoverflow.com/questions/56300950/pygsheet-operation-time-out-errno-60) Hope to somebody's help, thanks.

**Comment by nithinmurali** [comment]
Hey, for proxy can you check if the suggestion in for setting proxy #307 works?

**Comment by lidatou1991** [comment]
> Hey, for proxy can you check if the suggestion in for setting proxy #307 works?

Thanks for your reply.

I followed the instruction in [#307](https://github.com/nithinmurali/pygsheets/issues/307). Since I am using shadowsocks to access google. I changed my code in `client.py` by adding codes as follow:

`import httplib2

from httplib2 import socks

http_client = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_SOCKS5, '127.0.0.1', '1086'))
`
I change the `PROXY_TYPE_HTTP` to `PROXY_TYPE_SOCKS5` since it is what recommended in [question ](https://stackoverflow.com/questions/21345686/setting-proxy-on-httplib2).

On my mac the http proxy is 127.0.0.1:1088 and socks proxy is 127.0.0.1:1086. I am using google cloud vps 35.xx.55.xxx:xxxx

the error message is as following

`Traceback (most recent call last):
  File "gs-tw.py", line 9, in <module>
    wks = gc.open("test").sheet1
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/pygsheets/client.py", line 124, in open
    spreadsheet = list(filter(lambda x: x['name'] == title, self.drive.spreadsheet_metadata()))[0]
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/pygsheets/drive.py", line 122, in spreadsheet_metadata
    q=query)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/pygsheets/drive.py", line 80, in list
    response = self._execute_request(self.service.files().list(**kwargs))
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/pygsheets/drive.py", line 353, in _execute_request
    return request.execute(num_retries=self.retries)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google/oauth2/credentials.py", line 136, in refresh
    self._client_secret))
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 237, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/google_auth_httplib2.py", line 116, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1501, in _conn_request
    conn.connect()
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1356, in connect
    raise socket_err
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1289, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 60] Operation timed out`
