### ISSUE TITLE
Update cells  range in row

### ISSUE THREAD

**Issue by dimkoug** [nithinmurali/pygsheets#294]
**Describe the bug**
Can't update cell values in a row

**To Reproduce**
wks_sheet = Worksheet object
wks_sheet.update_values(crange='D2:E2', values=[[1],[2]],majordim='ROWS')
```
code here ...
Traceback (most recent call last):
  File "quickstart.py", line 204, in <module>
    get_data(data, gc, months)
  File "quickstart.py", line 118, in get_data
    wks_sheet.update_values(crange='D2:E2', values=[[1],[2]],majordim='ROWS')
  File "/home/dimitris/googlesheets/env/src/pygsheets/pygsheets/worksheet.py", line 618, in update_values
    self.client.sheet.values_batch_update(self.spreadsheet.id, body, parse)
  File "/home/dimitris/googlesheets/env/src/pygsheets/pygsheets/sheet.py", line 273, in values_batch_update
    self._execute_requests(request)
  File "/home/dimitris/googlesheets/env/src/pygsheets/pygsheets/sheet.py", line 351, in _execute_requests
    response = request.execute(num_retries=self.retries)
  File "/home/dimitris/googlesheets/env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)



```

**System Information**
 - OS: Ubuntu
 - pygsheets version : latest github version
 - pygsheets installed from (github or pypi): github

**Comment by dimkoug** [comment]
To update a range i used 

```
wks_sheet.update_values(crange='D2:E2', values=[[1,1]],majordim='ROWS')
```
