### ISSUE TITLE
IndexError: list index out of range with team drive enabled

### ISSUE THREAD

**Issue by jgillies** [nithinmurali/pygsheets#300]
**Description**
I get the follow exception when trying to create a file in a Team Drives folder:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    sh = gc.create('test', folder='[folder_id]')
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/pygsheets/client.py", line 98, in create
    old_folder=self.drive.spreadsheet_metadata(query="name = '" + title + "'")[0]['parents'][0],
IndexError: list index out of range
```
When I don't specify the folder, but keep Team Drives enabled, the file is created in my own drive.

**To Reproduce**
```
import pygsheets

gc = pygsheets.authorize()
gc.drive.enable_team_drive('[team_drive_id]')
sh = gc.create('test', folder='[folder_id]')

```

Team Drive ID is taken from here: `https://drive.google.com/drive/u/0/folders/[team_drive_id]?ogsrc=32`
Folder ID is take from here: `https://drive.google.com/drive/u/0/folders/[folder_id]?ogsrc=32`

**System Information**
 - OS: OSX
 - pygsheets version : 2.0.0
 - pygsheets installed from (github or pypi): github

**Comment by nithinmurali** [comment]
Hi, i have added a fix in staging. I could not test this as i don't have access to a teamdrive rt now. Please verify if this works.

`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip`

**Comment by jgillies** [comment]
Thanks for the quick response! Tried again with the fix and got this:

```
Traceback (most recent call last):
  File "pygsheets_test.py", line 15, in <module>
    sh = gc.create(sheet_name, folder='xxxxxxxxxxxx')
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/pygsheets/client.py", line 98, in create
    old_folder=self.drive.spreadsheet_metadata(query="name = '" + title + "'")[0]['parents'][0],
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/pygsheets/drive.py", line 111, in spreadsheet_metadata
    q=query)
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/pygsheets/drive.py", line 80, in list
    response = self._execute_request(self.service.files().list(**kwargs))
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/pygsheets/drive.py", line 348, in _execute_request
    return request.execute(num_retries=self.retries)
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/blah/.local/share/virtualenvs/pandas-qv6ELgRA/lib/python3.7/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files?corpora=user%2CteamDrive&teamDriveId=xxxxxxxxxx&supportsTeamDrives=true&includeTeamDriveItems=true&fields=files%28id%2C+name%2C+parents%29&q=name+%3D+%27xxxxxxxx%27+and+mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27&alt=json returned "Invalid Value">```

**Comment by jgillies** [comment]
This is working now. Thanks again for the quick fix!
