### ISSUE TITLE
Import error - on google apps

### ISSUE THREAD

**Issue by 2anoopgeorge** [nithinmurali/pygsheets#309]
**Describe the bug**
Python Code with pygsheets is working fine locally and google sheet is getting updated fine. But getting an error while it’s moved to google apps site. It’s uanble to import the ,double enum

ImportError: No module named enum  

**To Reproduce**
```
code here ...
# see error

 (/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/main.py", line 6, in <module>
    import pygsheets
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/__init__.py", line 14, in <module>
    from pygsheets.authorization import authorize
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/authorization.py", line 10, in <module>
    from pygsheets.client import Client
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/client.py", line 8, in <module>
    from pygsheets.drive import DriveAPIWrapper
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/drive.py", line 1, in <module>
    from pygsheets.spreadsheet import Spreadsheet
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/spreadsheet.py", line 14, in <module>
    from pygsheets.worksheet import Worksheet
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/worksheet.py", line 16, in <module>
    from pygsheets.cell import Cell
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/cell.py", line 11, in <module>
    from pygsheets.custom_types import *
  File "/base/data/home/apps/j~indane-inventory/20190117t063637.415464278070815935/lib/pygsheets/custom_types.py", line 11, in <module>
    from enum import Enum
ImportError: No module named enum  
```

**System Information**
 - pygsheets version :
 - pygsheets installed from (github or pypi):

**Comment by nithinmurali** [comment]
How did you install pygsheets? what is your python version?

**Comment by 2anoopgeorge** [comment]
I used the stable version and used the command pip install pygsheets
My local system python version is 3.7.2

As I mentioned it runs great on my local system; getting the error after moving it to google cloud and browse it using https://adreees.appspot.com

**Comment by nithinmurali** [comment]
Hi,  enum is added to std library of python3.4+. In your cloud account its using python2.7 which needs enum34 package. 

But its should be installed when pygsheets is [installed from pip](https://github.com/nithinmurali/pygsheets/blob/staging/setup.py#L41) . Anyway you can try to install it manually 'pip install enum34'. Else you can try changing python version in google apps.

**Comment by nithinmurali** [comment]
closing as there is no response. Please feel free to reopen.

**Comment by NitrosActive** [comment]
Hey nithinmurali, im trying to use pygsheets with conda, but its not working can u help me out here??

**Comment by nithinmurali** [comment]
@NitrosActive pygsheets is not available in conda. what exactly is the issue you are facing? please open a new issue if the error is unrelated.
