### ISSUE TITLE
Setting a cell's text foreground colour causes subsequent cell.update() calls to fail with "KeyError: 0"

### ISSUE THREAD

**Issue by alanmaydwell** [nithinmurali/pygsheets#340]
**Describe the bug**
I set a cell's text colour by supplying the values as a tuple and then called cell.update()

```
cell.set_text_format("foregroundColor", (0.5, 0.8, 0.5, 1.0))
cell.update()
```

The cell.update() step resulted in the following error:
```
cell.py", line 475, in get_json ret_json["userEnteredFormat"]["textFormat"]['foregroundColor'] = {"red": fg[0], "green": fg[1],
KeyError: 0
```
I've noticed cell.set_text_format converts the supplied colour tuple into a dictionary. Looks like ` `cell.update` is trying to get colour values from a tuple by index number but is getting a dictionary instead.

**To Reproduce**
Further details from Python console interactions.
```
>>> # Set text colour using tuple value							      
>>> cell.set_text_format("foregroundColor", (0.5, 0.8, 0.5, 1.0))
								      
<Cell E2 'sdf'>
>>> # Examine the foreground colour							      
>>> cell.text_format["foregroundColor"]   
{'red': 0.5, 'green': 0.8, 'blue': 0.5, 'alpha': 1.0}
>>> # From above see it's been automatically converted to a dictionary							      
>>> # Now try to update
>>> cell.update()
								      
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    cell.update()
  File "D:\Users\alan.maydwell\AppData\Local\Continuum\anaconda2\envs\py3\lib\site-packages\pygsheets\cell.py", line 431, in update
    "cell": self.get_json(),
  File "D:\Users\alan.maydwell\AppData\Local\Continuum\anaconda2\envs\py3\lib\site-packages\pygsheets\cell.py", line 475, in get_json
    ret_json["userEnteredFormat"]["textFormat"]['foregroundColor'] = {"red": fg[0], "green": fg[1],
KeyError: 0
>>> # Possibly the cell.py code above is expecting fg to be a tuple but is getting a dictionary instead.
```

**System Information**
 - OS: Windows
 - pygsheets version : 2.0.1
 - pygsheets installed from (github or pypi): pip

**Comment by ddow** [comment]
I'm getting this problem as well.
`row = self.sheet.get_row(self.row_count, returnas="range")
        for cell in row:
            cell.color = (0, 1, 0, 0)
        print()

  File "/Users/ddow/venv37/lib/python3.7/site-packages/pygsheets/cell.py", line 529, in __setattr__
    super(Cell, self).__setattr__(key, value)
  File "/Users/ddow/venv37/lib/python3.7/site-packages/pygsheets/cell.py", line 222, in color
    self.update()
  File "/Users/ddow/venv37/lib/python3.7/site-packages/pygsheets/cell.py", line 431, in update
    "cell": self.get_json(),
  File "/Users/ddow/venv37/lib/python3.7/site-packages/pygsheets/cell.py", line 475, in get_json
    ret_json["userEnteredFormat"]["textFormat"]['foregroundColor'] = {"red": fg[0], "green": fg[1],
KeyError: 0
`
