### ISSUE TITLE
Documentation bug: direct cell format assignment

### ISSUE THREAD

**Issue by DreadPirateShawn** [nithinmurali/pygsheets#363]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
The main README.md includes this example:
```
model_cell = Cell('A1')
model_cell.color = (1.0,0,1.0,1.0) # rose color cell
model_cell.format = pygsheets.FormatType.PERCENT
 # Setting format to multiple cells in one go
rng.apply_format(model_cell)  # will make all cell in this range rose color and percent format
```
However, this code triggers the following error:
```
Traceback (most recent call last):
...
  File "/highland/jira-to-sheets/venv/local/lib/python2.7/site-packages/pygsheets/datarange.py", line 228, in apply_format
    "cell": cell.get_json(),
  File "/highland/jira-to-sheets/venv/local/lib/python2.7/site-packages/pygsheets/cell.py", line 465, in get_json
    if self.format[0] is not None:
TypeError: 'FormatType' object does not support indexing
```
The problem is that the cell object's `.format` property is a tuple of (FormatType, pattern) -- not just FormatType.

Reference code from `cell.py`:
```
    def set_number_format(self, format_type, pattern=''):
        ...
        self.format = (format_type, pattern)
        self.update()
        return self
```

**To Reproduce**
See above.

**Expected Fix**
Probably just update the README.md to change
```
model_cell.format = pygsheets.FormatType.PERCENT
```
to
```
model_cell.set_number_format(pygsheets.FormatType.PERCENT)
```

**System Information**
 - OS: `Ubuntu 16.04 LTS`
 - pygsheets version: `pygsheets==2.0.1`
 - pygsheets installed from (github or pypi): `pypi`

**Comment by nithinmurali** [comment]
fixed
