### ISSUE TITLE
pygsheets.authorize custom_credentials returns returns error

### ISSUE THREAD

**Issue by bark-frank** [nithinmurali/pygsheets#412]
I'm using a secrets service that outputs in json format and I don't want to write a file, so I thought "custom_credentials" would facilitate this, but it returns this error:

```
Traceback (most recent call last):
  File "pygsheets-test.py", line 75, in <module>
    sh = gc.open(title)
  File "/usr/local/lib/python3.7/site-packages/pygsheets/client.py", line 120, in open
    spreadsheet = list(filter(lambda x: x['name'] == title, self.drive.spreadsheet_metadata()))[0]
  File "/usr/local/lib/python3.7/site-packages/pygsheets/drive.py", line 127, in spreadsheet_metadata
    q=query)
  File "/usr/local/lib/python3.7/site-packages/pygsheets/drive.py", line 85, in list
    response = self._execute_request(self.service.files().list(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/pygsheets/drive.py", line 364, in _execute_request
    return request.execute(num_retries=self.retries)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 186, in request
    self.credentials.before_request(
AttributeError: 'str' object has no attribute 'before_request'

shell returned 1
```

My auth code from [the auth page:](https://pygsheets.readthedocs.io/en/stable/authorization.html#custom-credentials-objects)
`gc = pygsheets.authorize(custom_credentials=my_credentials)`

I used a [work around found here](https://stackoverflow.com/questions/56817195/pygsheets-load-credentials-from-dict-instead-of-file), but now the problem is I'm writing temp files and even though I'm flushing them and they're disappearing afterwards, it's not the right (or secure) solution.

If "custom_credentials" is working as intended, I'm not sure how I can use it to create sheets and update cells.  Perhaps this needs to become a feature request for "pygsheets.authorize" to receive json output.

Thanks in advance for any help.

I'm using pygsheets 2.0.3 stable and python 3.7.

**Comment by nithinmurali** [comment]
The custom_credentials should be a credentials object as mentioned here. what you can do is 

```
SCOPES = ('https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive')
service_account_info = json.loads(secret)
my_credentials = service_account.Credentials.from_service_account_info(service_account_info, scopes=SCOPES)
```

**Comment by nithinmurali** [comment]
Added this to docs
