### ISSUE TITLE
Pip install problem

### ISSUE THREAD

**Issue by sosnicki** [nithinmurali/pygsheets#42]
Hi,

I have a problem with dependencies when i install pygsheets via pip. The 'enum' package cannot be installed

```
pip install pygsheets  
Collecting pygsheets
  Using cached pygsheets-0.2.1.tar.gz
Requirement already satisfied: google-api-python-client in /media/dane/sandbox/research/venv/lib/python3.5/site-packages (from pygsheets)
Collecting enum (from pygsheets)
  Using cached enum-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
        import platform
      File "/usr/lib/python3.5/platform.py", line 117, in <module>
        import sys, os, re, subprocess
      File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
        import signal
      File "/usr/lib/python3.5/signal.py", line 4, in <module>
        from enum import IntEnum as _IntEnum
    ImportError: cannot import name 'IntEnum'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ehvht6nd/enum/
```

I tried install it manually and when I remove 'enum' from the requirements in setup.py, the installation process  passed but I cannot import pygsheets:

```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygsheets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/pygsheets-0.2.1-py3.5.egg/pygsheets/__init__.py", line 15, in <module>
  File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/pygsheets-0.2.1-py3.5.egg/pygsheets/client.py", line 14, in <module>
  File "/media/dane/sandbox/research/venv/lib/python3.5/site-packages/pygsheets-0.2.1-py3.5.egg/pygsheets/models.py", line 17, in <module>
ImportError: No module named 'custom_types'
```

As you can see I'm using Python and virtual-env.

**Comment by nithinmurali** [comment]
Thanks for reporting, this. It's fixed in the pypi. Please verify if it working.

**Comment by sosnicki** [comment]
Thank you very much! It works like a charm.
