### ISSUE TITLE
Cannot import pygsheets

### ISSUE THREAD

**Issue by mattiadisalvo** [nithinmurali/pygsheets#476]
Hi all,

I am trying to import pygsheets but I get the error below. I have saved my Service credentials in .json in the same directory and correctly installed with pip install. What am I missing? Apologies if this could be rather obvious but could not find any other help online. 

Thanks,
Mattia

import pygsheets
Traceback (most recent call last):
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-7a9f06af3ec4>", line 1, in <module>
    import pygsheets
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/pygsheets/__init__.py", line 14, in <module>
    from pygsheets.authorization import authorize
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/pygsheets/authorization.py", line 8, in <module>
    from google_auth_oauthlib.flow import Flow, InstalledAppFlow
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/google_auth_oauthlib/__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/google_auth_oauthlib/interactive.py", line 24, in <module>
    import google_auth_oauthlib.flow
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 72, in <module>
    import google_auth_oauthlib.helpers
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/google_auth_oauthlib/helpers.py", line 28, in <module>
    import requests_oauthlib
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/requests_oauthlib/__init__.py", line 3, in <module>
    from .oauth1_auth import OAuth1
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/requests_oauthlib/oauth1_auth.py", line 7, in <module>
    from oauthlib.oauth1 import Client, SIGNATURE_HMAC, SIGNATURE_TYPE_AUTH_HEADER
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/oauthlib/oauth1/__init__.py", line 11, in <module>
    from .rfc5849 import Client
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 23, in <module>
    from . import parameters, signature
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/oauthlib/oauth1/rfc5849/parameters.py", line 14, in <module>
    from . import utils
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 14, in <module>
    import urllib2
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mattiadisalvo/PycharmProjects/Hello/venv/lib/python3.7/site-packages/urllib2.py", line 220
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax

**Comment by nithinmurali** [comment]
how did you install it?

**Comment by mattiadisalvo** [comment]
Hi,

I used pip install, with latest version of pip. Should I have done
differently?

**Comment by nithinmurali** [comment]
check if you can `import google_auth_oauthlib`

**Comment by mattiadisalvo** [comment]
hi, no I get the same error...

**Comment by nithinmurali** [comment]
Its looks like an issue with your environment and not within pygsheets. maybe you can try remove urllib2. try installing pygsheets in a new venv.

**Comment by mattiadisalvo** [comment]
Thank you very much, it worked! Have a nice day
