### ISSUE TITLE
Error on adding a row to the table

### ISSUE THREAD

**Issue by exactstat** [nithinmurali/pygsheets#563]
In an attempt to add the first row to the empty table.  

```
 File "*******\venv\lib\site-packages\pygsheets\utils.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "*******\venv\lib\site-packages\pygsheets\worksheet.py", line 1148, in append_table
    'tableRange': GridRange.create(response_json['tableRange'], self),
KeyError: 'tableRange'
```
and the response_json itself  

```
{
  'spreadsheetId': '*******',
  'updates': {
    'spreadsheetId': '**********',
    'updatedRange': "'********'!A1:F1",
    'updatedRows': 1,
    'updatedColumns': 6,
    'updatedCells': 6
  }
}
```

**Comment by tastyminerals** [comment]
Not sure if it got fixed, I am still having this issue
```
Traceback (most recent call last):
  File "/Users/pavels/reporting/report.py", line 298, in <module>
    main()
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavels/reporting/report.py", line 293, in main
    customer_sheet.append_table(list(csv_row.values()))
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/pygsheets/utils.py", line 214, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavels/Library/Caches/pypoetry/virtualenvs/reporting-8QrzVxZu-py3.12/lib/python3.12/site-packages/pygsheets/worksheet.py", line 1148, in append_table
    'tableRange': GridRange.create(response_json['tableRange'], self),
```
