### ISSUE TITLE
Team Drive Access is Working But not for Team Drives I don't own

### ISSUE THREAD

**Issue by casalemi** [nithinmurali/pygsheets#81]
Hi Nithan,

The Team Drive functionality is working for Team Drives I own.  However, I want to use the same creds (i.e., the email address) on a Team Drive I do not own.  When I run the same exact test using that Team Drive ID for an existing spreadsheet, this is the result:

C:\Users\xxx\Downloads\Nithin\test>python Chris_team_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 154, in open
    ssheet_id = [x['id'] for x in self._spreadsheeets if x["name"] == title][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Chris_team_drive.py", line 15, in <module>
    ss = gc.open('Plug-in Costs')
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 157, in open
    self._fetch_sheets()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 86, in _fetch_sheets
    results = self._execute_request(None, request, False)
  File "C:\Users\salech01\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 381, in _execute_request
    response = request.execute()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\oauth2client-4.1.0-py3.6.egg\oauth2client\_helpers.py", line 133, in positional_wrapper
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\google_api_python_client-1.6.2-py3.6.egg\googleapiclient\http.py", line 840, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?corpora=teamDrive&pageSize=500&fields=files%28id%2C+name%29&teamDriveId=xxx%60&q=mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27&supportsTeamDrives=true&includeTeamDriveItems=true&alt=json returned "Team Drive not found: xxx`">

C:\Users\xxx\Downloads\Nithin\test>

Are there other attributes that can be provided that would make this work for Team Drive I do not own?

**Comment by nithinmurali** [comment]
Drive api gives only this much [acess](https://developers.google.com/drive/v3/reference/files/list). I dont see any other attribute. But logically if you can access a teamDrive, then you should be able to access it from the api too. Make sure its shared with the service account you are using.

**Comment by casalemi** [comment]
The Team Drive is shared with the email address in the Service Account.  The file is on the Team Drive however it is in a sub-folder on that Team Drive whereas when I tested on my Team Drive it was at the root of the folder.  Would that make a difference?

**Comment by nithinmurali** [comment]
No, I dont think it would make a difference. If you look at the error, its saying it cant find the teamdrive. Make sure your teamdrive ID is correct?

**Comment by casalemi** [comment]
Sorry Nithin.  It is working I fat-fingered and extra character in the Team Drive ID.  You can close this issue.  Thanks!
