### ISSUE TITLE
Not the actual instruction, the creating wks, a problem with the wks.

### ISSUE THREAD

**Issue by vladiscripts** [nithinmurali/pygsheets#95]
In the instruction no sample for create Worksheet. Then I tried `sh = gc.create('my new ssheet')` , and run sample from instruction:
```
gc = pygsheets.authorize(outh_file=CREDENTIALS_FILE)
sh = gc.create('my new ssheet')
wks = sh.sheet1

# or achive the same in oneliner
wks.cell('B1').set_text_format('bold', True).value = 'heights' 
```
```
Traceback (most recent call last):
  File "/home/vladislav/workspace/python_tests/google_sheets.py", line 49, in <module>
    wks.cell('B1').set_text_format('bold', True).value = 'heights'
  File "/home/vladislav/miniconda3/lib/python3.6/site-packages/pygsheets/cell.py", line 186, in set_text_format
    self.fetch()
  File "/home/vladislav/miniconda3/lib/python3.6/site-packages/pygsheets/cell.py", line 276, in fetch
    result = result['sheets'][0]['data'][0]['rowData'][0]['values'][0]
KeyError: 'rowData'
```

No error if instead the string above use:
```
header = wks.cell('A1')
header.value = 'Names'
header.text_format['bold'] = True # make the header bold
header.update()
```
But on strings:
```
# set the heights
heights = wks.range('B2:B5')  # get the range
heights.name = "heights"  # name the range
```
follow error:
```
    heights.name = "heights"  # name the range
AttributeError: 'list' object has no attribute 'name'
```

**Comment by nithinmurali** [comment]
About the 2nd error, ` wks.range('B2:B5')` wont return a range object by defaut (it returns a cell matrix) . Here you are trying to create a named range. So you need to create a `DataRange` object. So use this
```
heights = wks.range('B2:B5', returnas='range')
```

**Comment by vladiscripts** [comment]
it works, thanx

**Comment by nithinmurali** [comment]
Thanks for reporting this. Have pushed a fix to first problem. Install pygsheets by 
`pip install https://github.com/nithinmurali/pygsheets/archive/master.zip` to get the fix.
